{
 "title": "Bridge",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "bridgeName",
    "label": "Bridge",
    "query": "label_values({__name__=~\"ncache_bridge_.*\"},bridge_id)"
   },
   {
    "name": "cache",
    "label": "Bridge Cache",
    "query": "label_values({bridge_id=~\"$bridgeName\"},cache_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Bridge Cache Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ncache_bridge_cache_size{is_mirror=\"False\",bridge_id=~\"$bridgeName|\"}",
     "legendFormat": "{{bridge_id}} [{{server}}] Active"
    },
    {
     "expr": "ncache_bridge_cache_size{is_mirror=\"True\",bridge_id=~\"$bridgeName|\"}",
     "legendFormat": "{{bridge_id}} [{{server}}] Replica"
    }
   ]
  },
  {
   "title": "Bridge Cache Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ncache_bridge_cache_count{is_mirror=\"False\",bridge_id=~\"$bridgeName|\"}",
     "legendFormat": "{{bridge_id}} [{{server}}] Active"
    },
    {
     "expr": "ncache_bridge_cache_count{is_mirror=\"True\",bridge_id=~\"$bridgeName|\"}",
     "legendFormat": "{{bridge_id}} [{{server}}] Replica"
    }
   ]
  },
  {
   "title": "Bridge Operations Sent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ncache_bridge_operations_sent{is_mirror=\"False\",bridge_id=~\"$bridgeName|\"}",
     "legendFormat": "{{bridge_id}} [{{server}}] Active"
    },
    {
     "expr": "ncache_bridge_operations_sent{is_mirror=\"True\",bridge_id=~\"$bridgeName|\"}",
     "legendFormat": "{{bridge_id}} [{{server}}] Replica"
    }
   ]
  },
  {
   "title": "Bridge Operations Sent/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ncache_bridge_operations_sent_per_sec{is_mirror=\"False\",bridge_id=~\"$bridgeName|\"}",
     "legendFormat": "{{bridge_id}} [{{server}}] Active"
    },
    {
     "expr": "ncache_bridge_operations_sent_per_sec{is_mirror=\"True\",bridge_id=~\"$bridgeName|\"}",
     "legendFormat": "{{bridge_id}} [{{server}}] Replica"
    }
   ]
  },
  {
   "title": "Bridge Operations Received",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ncache_bridgedcache_operations_received{cache_id=~\"$cache|\",bridge_id=~\"$bridgeName|\"}",
     "legendFormat": "{{bridge_id}} {{cache_id}} [{{server}}]"
    },
    {
     "expr": "ncache_bridge_operations_received{is_mirror=\"False\",bridge_id=~\"$bridgeName|\"}",
     "legendFormat": "{{bridge_id}} [{{server}}] Active"
    },
    {
     "expr": "ncache_bridge_operations_received{is_mirror=\"True\",bridge_id=~\"$bridgeName|\"}",
     "legendFormat": "{{bridge_id}} [{{server}}] Replica"
    }
   ]
  },
  {
   "title": "Bridge Operations Received/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ncache_bridgedcache_operations_received_per_sec{cache_id=~\"$cache|\",bridge_id=~\"$bridgeName|\"}",
     "legendFormat": "{{bridge_id}} {{cache_id}} [{{server}}]"
    },
    {
     "expr": "ncache_bridge_operations_received_per_sec{is_mirror=\"False\",bridge_id=~\"$bridgeName|\"}",
     "legendFormat": "{{bridge_id}} [{{server}}] Active"
    },
    {
     "expr": "ncache_bridge_operations_received_per_sec{is_mirror=\"True\",bridge_id=~\"$bridgeName|\"}",
     "legendFormat": "{{bridge_id}} [{{server}}] Replica"
    }
   ]
  },
  {
   "title": "Queue Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ncache_bridge_queue_count{is_mirror=\"False\",bridge_id=~\"$bridgeName|\"}",
     "legendFormat": "{{bridge_id}} [{{server}}] Active"
    },
    {
     "expr": "ncache_bridge_queue_count{is_mirror=\"True\",bridge_id=~\"$bridgeName|\"}",
     "legendFormat": "{{bridge_id}} [{{server}}] Replica"
    }
   ]
  },
  {
   "title": "Replicator Queue Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ncache_bridgedcache_replicator_queue_count{cache_id=~\"$cache|\",bridge_id=~\"$bridgeName|\"}",
     "legendFormat": "{{bridge_id}} {{cache_id}} [{{server}}]"
    }
   ]
  },
  {
   "title": "Replicator Queue Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ncache_bridgedcache_replicator_queue_size{cache_id=~\"$cache|\",bridge_id=~\"$bridgeName|\"}",
     "legendFormat": "{{bridge_id}} {{cache_id}} [{{server}}]"
    }
   ]
  }
 ]
}