{
 "title": "Cache",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cache",
    "label": "Cache",
    "query": "label_values({__name__=~\"$counters\"},cache_id)"
   },
   {
    "name": "Node",
    "label": "Server",
    "query": "label_values({cache_id=~\"$cache\"},server)"
   },
   { "name": "counters", "label": "NCache Cache Counters", "query": "label_values(__name__)" }
  ]
 },
 "panels": [
  {
   "title": "Request/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ncache_requests_per_sec{is_mirror=\"False\",cache_id=~\"$cache|\",server=~\"$Node|\"}",
     "legendFormat": "{{cache_id}}[{{server}}] Active"
    },
    {
     "expr": "ncache_requests_per_sec{is_mirror=\"True\",cache_id=~\"$cache|\",server=~\"$Node|\"}",
     "legendFormat": "{{cache_id}}[{{server}}] Replica"
    }
   ]
  },
  {
   "title": "Average us/Cache Operations",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ncache_average_us_per_cache_operation{is_mirror=\"False\",cache_id=~\"$cache|\",server=~\"$Node|\"}",
     "legendFormat": "{{cache_id}}[{{server}}] Active"
    },
    {
     "expr": "ncache_average_us_per_cache_operation{is_mirror=\"True\",cache_id=~\"$cache|\",server=~\"$Node|\"}",
     "legendFormat": "{{cache_id}}[{{server}}] Replica"
    }
   ]
  },
  {
   "title": "Additions/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ncache_additions_per_sec{is_mirror=\"False\",cache_id=~\"$cache|\",server=~\"$Node|\"}",
     "legendFormat": "{{cache_id}}[{{server}}] Active"
    },
    {
     "expr": "ncache_additions_per_sec{is_mirror=\"True\",cache_id=~\"$cache|\",server=~\"$Node|\"}",
     "legendFormat": "{{cache_id}}[{{server}}] Replica"
    }
   ]
  },
  {
   "title": "Fetches/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ncache_fetches_per_sec{is_mirror=\"False\",cache_id=~\"$cache|\", server=~\"$Node|\"}",
     "legendFormat": "{{cache_id}}[{{server}}] Active"
    },
    {
     "expr": "ncache_fetches_per_sec{is_mirror=\"True\",cache_id=~\"$cache|\", server=~\"$Node|\"}",
     "legendFormat": "{{cache_id}}[{{server}}] Replica"
    }
   ]
  },
  {
   "title": "Updates/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ncache_updates_per_sec{is_mirror=\"False\",cache_id=~\"$cache|\", server=~\"$Node|\"}",
     "legendFormat": "{{cache_id}}[{{server}}] Active"
    },
    {
     "expr": "ncache_updates_per_sec{is_mirror=\"True\",cache_id=~\"$cache|\", server=~\"$Node|\"}",
     "legendFormat": "{{cache_id}}[{{server}}] Replica"
    }
   ]
  },
  {
   "title": "Deletes/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ncache_deletes_per_sec{is_mirror=\"False\",cache_id=~\"$cache|\", server=~\"$Node|\"}",
     "legendFormat": "{{cache_id}}[{{server}}] Active"
    },
    {
     "expr": "ncache_deletes_per_sec{is_mirror=\"True\",cache_id=~\"$cache|\", server=~\"$Node|\"}",
     "legendFormat": "{{cache_id}}[{{server}}] Replica"
    }
   ]
  },
  {
   "title": "Cache Size (MB)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ncache_cache_size{is_mirror=\"False\",cache_id=~\"$cache|\",server=~\"$Node|\"}/1048576",
     "legendFormat": "{{cache_id}}[{{server}}] Active"
    },
    {
     "expr": "ncache_cache_size{is_mirror=\"True\",cache_id=~\"$cache|\",server=~\"$Node|\"}/1048576",
     "legendFormat": "{{cache_id}}[{{server}}] Replica"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ncache_cpu_usage{server_ip=~\"$Node|\"}",
     "legendFormat": "{{server_ip}}"
    }
   ]
  },
  {
   "title": "NCache Memory Usage (MB)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ncache_memory_usage{server_ip=~\"$Node|\"}",
     "legendFormat": "{{server_ip}}"
    }
   ]
  },
  {
   "title": "Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ncache_count{is_mirror=\"False\",cache_id=~\"$cache|\",server=~\"$Node|\"}",
     "legendFormat": "{{cache_id}}[{{server}}] Active"
    },
    {
     "expr": "ncache_count{is_mirror=\"True\",cache_id=~\"$cache|\",server=~\"$Node|\"}",
     "legendFormat": "{{cache_id}}[{{server}}] Replica"
    }
   ]
  },
  {
   "title": "Expirations/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ncache_expirations_per_sec{is_mirror=\"False\",cache_id=~\"$cache|\", server=~\"$Node|\"}",
     "legendFormat": "{{cache_id}}[{{server}}] Active"
    },
    {
     "expr": "ncache_expirations_per_sec{is_mirror=\"True\",cache_id=~\"$cache|\", server=~\"$Node|\"}",
     "legendFormat": "{{cache_id}}[{{server}}] Replica"
    }
   ]
  },
  {
   "title": "Evictions/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ncache_evictions_per_sec{is_mirror=\"False\",cache_id=~\"$cache|\", server=~\"$Node|\"}",
     "legendFormat": "{{cache_id}}[{{server}}] Active"
    },
    {
     "expr": "ncache_expirations_per_sec{is_mirror=\"True\",cache_id=~\"$cache|\", server=~\"$Node|\"}",
     "legendFormat": "{{cache_id}}[{{server}}] Replica"
    }
   ]
  }
 ]
}