{
 "title": "Client",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cache",
    "label": "Cache",
    "query": "label_values({__name__=~\"ncache_client_.*\"}, cache_id)"
   },
   {
    "name": "client",
    "label": "Client",
    "query": "label_values({cache_id=~\"$cache\"}, client_ip)"
   }
  ]
 },
 "panels": [
  {
   "title": "Average Item Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ncache_client_average_item_size{client_ip=~\"$client|\" ,cache_id=~\"$cache|\"}",
     "legendFormat": "{{cache_id}}[{{client_ip}}]"
    }
   ]
  },
  {
   "title": "Read Operations/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ncache_client_read_operations_per_sec{client_ip=~\"$client|\" ,cache_id=~\"$cache|\"}",
     "legendFormat": "{{cache_id}}[{{client_ip}}]"
    }
   ]
  },
  {
   "title": "Write Operations/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ncache_client_write_operations_per_sec{client_ip=~\"$client|\" ,cache_id=~\"$cache|\"}",
     "legendFormat": "{{cache_id}}[{{client_ip}}]"
    }
   ]
  },
  {
   "title": "Additions/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ncache_client_additions_per_sec{client_ip=~\"$client|\" ,cache_id=~\"$cache|\"}",
     "legendFormat": "{{cache_id}}[{{client_ip}}]"
    }
   ]
  },
  {
   "title": "Updates/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ncache_client_updates_per_sec{client_ip=~\"$client|\" ,cache_id=~\"$cache|\"}",
     "legendFormat": "{{cache_id}}[{{client_ip}}]"
    }
   ]
  },
  {
   "title": "Fetches/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ncache_client_fetches_per_sec{client_ip=~\"$client|\" ,cache_id=~\"$cache|\"}",
     "legendFormat": "{{cache_id}}[{{client_ip}}]"
    }
   ]
  },
  {
   "title": "Avg us/Add",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ncache_client_average_us_per_add{client_ip=~\"$client|\" ,cache_id=~\"$cache|\"}",
     "legendFormat": "{{cache_id}}[{{client_ip}}]"
    }
   ]
  },
  {
   "title": "Avg us/Update",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ncache_client_average_us_per_insert{client_ip=~\"$client|\" ,cache_id=~\"$cache|\"}",
     "legendFormat": "{{cache_id}}[{{client_ip}}]"
    }
   ]
  },
  {
   "title": "Avg us/Fetch",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ncache_client_average_us_per_fetch{client_ip=~\"$client|\" ,cache_id=~\"$cache|\"}",
     "legendFormat": "{{cache_id}}[{{client_ip}}]"
    }
   ]
  }
 ]
}